apiVersion: v1
kind: Service
metadata:
  name: express-app-service
spec:
  selector:
    app: express-app
  ports:
    - name: express-app-service-port
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30005
  type: NodePort
