apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    db: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql-db
  template:
    metadata:
      labels:
        db: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret-file
                  key: mysql_root_pass
          volumeMounts:
            - name: config-map
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: config-map
          configMap:
            name: app-configmap
            items:
              - key: "mysql-schema.sql"
                path: "mysql-schema.sql"
