apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    db: mysql-db
spec:
  selector:
    matchLabels:
      db: mysql-db
  template:
    metadata:
      labels:
        db: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASS
              valueFrom:
                secretKeyRef:
                  name: mysecret-file
                  key: mysql_root_pass
